# Generated by Django 3.0.14 on 2023-01-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, upload_to='instagram/post/%Y/%m/%d'),
        ),
    ]
